services:
  mysql:
    image: mysql:8
    container_name: vote_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SECRET_PASSWORD
      MYSQL_DATABASE: vote_database
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
